# Generated by Django 3.1.7 on 2021-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleset',
            name='air_temperature',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
