# Generated by Django 3.1.7 on 2021-04-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_set', '0002_auto_20210409_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleset',
            name='sample_depth',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='sample_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='sample_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='water_temperature',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
