# Generated by Django 3.1.7 on 2021-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_set', '0002_sampleset_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersurface',
            name='property',
            field=models.CharField(blank=True, choices=[('Oil', 'Oily surface'), ('Foam', 'Foamy surface'), ('Bioluminescence', 'Bioluminescent')], max_length=20),
        ),
    ]
