# Generated by Django 3.1.7 on 2021-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_set', '0003_auto_20210415_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathercondition',
            name='sample',
        ),
        migrations.AddField(
            model_name='sampleset',
            name='water_bioluminescence',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='water_foam',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='water_oil',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='weather_cloud',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='weather_rain',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='weather_snow',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='weather_storm',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sampleset',
            name='weather_sun',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='WaterSurface',
        ),
        migrations.DeleteModel(
            name='WeatherCondition',
        ),
    ]
