# Generated by Django 3.1.7 on 2021-04-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_set', '0004_auto_20210415_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleset',
            name='water_bioluminescence',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='water_foam',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='water_oil',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='weather_cloud',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='weather_rain',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='weather_snow',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='weather_storm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sampleset',
            name='weather_sun',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
