# Generated by Django 3.1.7 on 2021-04-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_set', '0005_auto_20210415_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleset',
            options={'ordering': ['-id']},
        ),
    ]
