# Generated by Django 3.1.7 on 2021-08-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_set', '0006_auto_20210420_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleset',
            options={'ordering': (['-id'],)},
        ),
    ]
