# Generated by Django 3.1.7 on 2021-09-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_set', '0007_auto_20210827_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleset',
            options={'ordering': ['id']},
        ),
    ]
