# Generated by Django 3.1.7 on 2021-04-12 11:21

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RE', 'Registration Email'), ('PR', 'Password Reset')], default='RE', max_length=2)),
                ('code', models.CharField(default=registration.models.code_generator, max_length=6)),
                ('used', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
