# Generated by Django 3.1.7 on 2021-04-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample_set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='')),
                ('annotated_image', models.ImageField(blank=True, upload_to='')),
                ('marker_state', models.JSONField(blank=True)),
                ('zooplankton', models.IntegerField(blank=True, default=0)),
                ('phytoplankton', models.IntegerField(blank=True, default=0)),
                ('plastic_fibers', models.IntegerField(blank=True, default=0)),
                ('plastic_particles', models.IntegerField(blank=True, default=0)),
                ('sample_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='sample_set.sampleset')),
            ],
        ),
    ]
