# Generated by Django 3.1.7 on 2021-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='marker_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
