# Generated by Django 3.1.7 on 2021-04-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('sample_set', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sample_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='sample_set.sampleset'),
        ),
    ]
