# Generated by Django 3.1.7 on 2021-04-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_sample_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='annotated_image',
            field=models.TextField(blank=True),
        ),
    ]
