# Generated by Django 3.1.7 on 2021-04-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.IntegerField(choices=[(1, 'plankton mode'), (2, 'dark mode'), (3, 'light mode')], default=1, max_length=1),
        ),
    ]
